### PR TITLE
Add values for HTTPProxyServer

### PR DESCRIPTION
**Pull request by Rizato**
Includes some changes from mwp that are necessary to run with psd3.

### CODE REVIEW

**Comment by Rizato** [comment]
I removed the tests from CI because they will kill our rate limit with clamav.

**Review by alanjds — APPROVED** [review]
Rate limit on clamav? How curious is that.

**Comment by Rizato** [comment]
> Rate limit on clamav? How curious is that.

It's a rate limit on downloading updates

**Comment by alanjds** [comment]
> It's a rate limit on downloading updates

Got it. Thanks.

**Pull request merged**
